Repository hellocarla/nachitos, pull requests merged in 2023-12, with the labels that each got.

#11 Alterações
  app/models/recomendacoes.js
  app/models/surtos.js
  lista_paises.js
  lista_recomendacoes.js
  lista_surtos.js
  lista_virus.js
  lista_zonas.js
  package-lock.json
  package.json
  routes/routePaises.js
  routes/routeRecomendacoes.js
  routes/routeSurtos.js
  routes/routeVirus.js
Labels: documentation

#12 13122023 -- File Organization + API skeleton + Joi validation
  API1_OMS/DataBase_Template/lista_paises.js
  API1_OMS/DataBase_Template/lista_recomendacoes.js
  API1_OMS/DataBase_Template/lista_surtos.js
  API1_OMS/DataBase_Template/lista_virus.js
  API1_OMS/DataBase_Template/lista_zonas.js
  API1_OMS/app/.DS_Store
  API1_OMS/app/models/funcionarios.js
  API1_OMS/app/models/paises.js
  API1_OMS/app/models/recomendacoes.js
  API1_OMS/app/models/surtos.js
  API1_OMS/app/models/virus.js
  API1_OMS/app/models/zona.js
  API1_OMS/routes/routePaises.js
  API1_OMS/routes/routeRecomendacoes.js
  API1_OMS/routes/routeSurtos.js
  API1_OMS/routes/routeVirus.js
  API1_OMS/routes/routeZona.js
  API1_OMS/server.js
  README.md
  SafetyTourism/README.md
  SafetyTourism/controllers/destinationsController.js
  SafetyTourism/models/destinations.js
  SafetyTourism/models/packages.js
  SafetyTourism/models/reservations.js
  SafetyTourism/models/users.js
  SafetyTourism/privateREADME.md
  SafetyTourism/routes/destinationsRoutes.js
  SafetyTourism/theserver.js
  playground-1.mongodb.js
  routes/routeFuncionarios.js
Labels: documentation

#13 15122023 -- destination updates
  SafetyTourism/controllers/destinationsController.js
  SafetyTourism/models/destinations.js
  SafetyTourism/routes/destinationsRoutes.js
  SafetyTourism/theserver.js
Labels: documentation

#16 CV_SafTou_UsersRegister
  SafetyTourism/README.md
  SafetyTourism/controllers/destinationsController.js
  SafetyTourism/controllers/usersController.js
  SafetyTourism/models/users.js
  SafetyTourism/routes/usersRoutes.js
  SafetyTourism/theserver.js
Labels: documentation

#17 Ligação da reserva aos users e pacotes.
  SafetyTourism/controllers/reservationsController.js
  SafetyTourism/models/packages.js
  SafetyTourism/models/reservations.js
  SafetyTourism/models/users.js
Labels: bug, documentation

#19 ligação APIs e GETs de surtos ativos
  API1_OMS/routes/routePaises.js
  API1_OMS/routes/routeSurtos.js
  API1_OMS/server.js
  SafetyTourism/controllers/countryController.js
  SafetyTourism/controllers/destinationsController.js
  SafetyTourism/controllers/usersController.js
  SafetyTourism/routes/countryRoutes.js
  SafetyTourism/routes/destinationsRoutes.js
  SafetyTourism/routes/usersRoutes.js
  SafetyTourism/theserver.js
  package-lock.json
  package.json
Labels: documentation, rollback
